### ISSUE TITLE
"name" as name for "$" variable

### ISSUE THREAD

**Issue by msaunby** [jacobtomlinson/datapoint-js#17]
If I was going to pick a descriptive name for the obs timestep value '$' I'd probably go with "minutes". "name" looks like a mistake.

**Comment by jacobtomlinson** [comment]
I think I picked it because `name` is what it is called in the XML feed. Note the lack of consistency.

`minutes` would be suitable for the 3hourly forecast where it returns minutes since midnight, however in the forecast daily the values are `day` and `night`.
